#ifndef LV_CONF_H
#define LV_CONF_H

#define LV_COLOR_DEPTH 16
#define LV_MEM_SIZE (2U * 1024U * 1024U)
#define LV_USE_LOG 0
#define LV_USE_ASSERT_NULL 1
#define LV_USE_ASSERT_MALLOC 1
#define LV_USE_OS LV_OS_NONE
#define LV_USE_STDLIB_MALLOC LV_STDLIB_BUILTIN
#define LV_USE_STDLIB_STRING LV_STDLIB_BUILTIN
#define LV_USE_STDLIB_SPRINTF LV_STDLIB_BUILTIN
#define LV_FONT_MONTSERRAT_14 1
#define LV_FONT_DEFAULT &lv_font_montserrat_14
#define LV_USE_LABEL 1
#define LV_USE_BUTTON 1
#define LV_USE_SWITCH 1
#define LV_USE_SLIDER 1
#define LV_USE_ARC 1
#define LV_USE_BAR 1
#define LV_USE_CHECKBOX 1
#define LV_USE_DROPDOWN 1
#define LV_USE_ROLLER 1
#define LV_USE_TEXTAREA 1
#define LV_USE_KEYBOARD 1
#define LV_USE_TILEVIEW 1
#define LV_USE_TABVIEW 1
#define LV_USE_LED 1
#define LV_USE_SPINNER 1
#define LV_USE_QRCODE 1
#define LV_USE_SPINBOX 1
#define LV_USE_IMAGE 1
#define LV_USE_ANIMIMG 1
#define LV_USE_SCALE 1
#define LV_USE_LINE 1
#define LV_USE_CANVAS 1

#endif
